# Generated by Django 5.0.6 on 2024-05-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=400, unique=True)),
                ("base_title", models.CharField(max_length=1000)),
                ("base_content", models.TextField()),
                ("groq_title", models.CharField(blank=True, max_length=1000)),
                ("groq_content", models.TextField(blank=True)),
                ("groq_key_point_1", models.CharField(blank=True, max_length=1000)),
                ("groq_key_point_2", models.CharField(blank=True, max_length=1000)),
                ("groq_key_point_3", models.CharField(blank=True, max_length=1000)),
                ("groq_question_1", models.CharField(blank=True, max_length=1000)),
                ("groq_question_2", models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
