# Generated by Django 5.0.6 on 2024-05-25 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news_feed", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="groq_content",
        ),
    ]
