# Generated by Django 5.0.6 on 2024-05-25 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_feed", "0002_remove_news_groq_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="base_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="date_added",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
